### ISSUE TITLE
Open in Vim with keyboard shortcut

### ISSUE THREAD

**Issue by fresh2dev** [babakks/vscode-open-with-vim#5]
Thanks for the stellar plugin! I've been dreaming about something like this for a while, but it seems to fall short in one area, and it's sort of ironic: I can't open in Vim with a *keyboard shortcut*.

I can right click > "Open with Vim..." and all is well. But when I define a keyboard shortcut, it does not work.

> keybindings.json

```json
[
    {
        "key": "o",
        "command": "vscode-open-with-vim.openWithVim",
        "when": "explorerViewletFocus && foldersViewVisible && !inputFocus"
    }
]
```

With this, when I press "o" in the file explorer, VSCode reports this error:

```
Cannot read properties of undefined (reading 'toString')
```

Any ideas?

**Comment by babakks** [comment]
@fresh2dev Thanks for reporting this, and sorry for the delay. The solution to this is a bit hacky, because at the moment VS Code does not provide an API to get the selected file in the explorer tree. You can see the long discussion [here](https://github.com/Microsoft/vscode/issues/3553).

Anyway, I managed to use one of the suggestions in the mentioned thread to make this work. I just published a new version of the extension. Could you please upgrade to v0.0.5, and let me know if this works for you?
